---


- name: common
  tags: common
  hosts: all localhost
  vars:
      setupsoftware_dir: "{{ ansible_env.HOME}}/.local/share/setupsoftware/"
  roles:
      - role: common

- name: workstation
  tags: workstation
  hosts: all localhost
  vars:
      setupsoftware_dir: "{{ ansible_env.HOME}}/.local/share/setupsoftware/"
  roles:
      - role: common
      - role: workstation

- name: zfs-server
  tags: zfs-server
  hosts: all localhost
  vars:
      setupsoftware_dir: "{{ ansible_env.HOME}}/.local/share/setupsoftware/"
  roles:
      - role: common
      - role: zfs

- name: zfs-workstation
  tags: zfs-workstation
  hosts: all localhost
  vars:
      setupsoftware_dir: "{{ ansible_env.HOME}}/.local/share/setupsoftware/"
  roles:
      - role: common
      - role: workstation
      - role: zfs

- name: laptop
  tags: laptop
  hosts: all localhost
  vars:
      setupsoftware_dir: "{{ ansible_env.HOME}}/.local/share/setupsoftware/"
  roles:
      - role: common
      - role: workstation
      - role: laptop

- name: zfs-laptop
  tags: zfs-laptop
  hosts: all localhost
  vars:
      setupsoftware_dir: "{{ ansible_env.HOME}}/.local/share/setupsoftware/"
  roles:
      - role: common
      - role: workstation
      - role: laptop
      - role: zfs

- name: x220
  tags: x220
  hosts: all localhost
  vars:
      setupsoftware_dir: "{{ ansible_env.HOME}}/.local/share/setupsoftware/"
  roles:
      - role: common
      - role: workstation
      - role: laptop
      - role: x220
      - role: zfs

- name: t430
  tags: t430
  hosts: all localhost
  vars:
      setupsoftware_dir: "{{ ansible_env.HOME}}/.local/share/setupsoftware/"
  roles:
      - role: common
      - role: workstation
      - role: laptop
      - role: t430
      - role: zfs

