#!/bin/sh

# This script was originally sourced from
#
# https://nrocco.github.io/2014/06/05/suspend_prevent-systemd.html

set -e

if [ "$(whoami)" != "root" ] ; then
	echo "ERROR: must be run as root!" > /dev/stderr
	exit 1
fi

case "$1" in
    battery)
        echo 'Running on battery. Making sure to remove the inhibit lock'
        systemctl stop suspend_prevent.service
        ;;

    ac)
        echo 'Running on AC. Making sure to add the inhibit lock'
        systemctl start suspend_prevent.service
        ;;

    -h|--help|help)
        echo "Usage: $(basename $0) [battery|ac|--forever]"
        exit 1
        ;;

    --forever)
        systemd-inhibit --what=handle-lid-switch:sleep --who=$(id -un $(whoami)) --why="Prevent suspend on lid close when on AC" --mode=block bash -c "while true; do sleep 60; done"
        ;;

    *)
        echo 'Automatically detecting power source...'

        if cat /sys/class/power_supply/AC/online | grep 0 > /dev/null 2>&1
        then
            $0 battery
        else
            $0 ac
        fi

        exit $?
        ;;
esac

exit 0
