---
- name: Install Services
  template: src={{ item }}.service.j2 dest=/etc/systemd/system/{{ item }}.service
  become: yes
  become_user: root
  become_method: sudo
  with_items:
      - xhci_reset

- name: Enable Services
  service: name={{ item }}.service enabled=yes
  become: yes
  become_user: root
  become_method: sudo
  with_items:
      - xhci_reset

- name: Install Intel Xorg Driver
  apt: pkg={{ item }} state=latest
  with_items:
      - xserver-xorg-video-intel
  become: yes
  become_user: root
  become_method: sudo

- name: Install backlight workaround
  template:
      src: grub.j2
      dest: /etc/default/grub
  become: yes
  become_user: root
  become_method: sudo
  notify: update grub
