---
- name: Install Services
  template: src={{ item }}.service.j2 dest=/etc/systemd/system/{{ item }}.service
  become: yes
  become_user: root
  become_method: sudo
  with_items:
      - xhci_reset

- name: Enable Services
  service: name={{ item }}.service enabled=yes
  become: yes
  become_user: root
  become_method: sudo
  with_items:
      - xhci_reset

- name: Install nVidia Xorg Driver
  apt: pkg={{ item }} state=latest
  with_items:
      - nvidia-egl-icd
      - nvidia-driver-libs
      - nvidia-driver
  become: yes
  become_user: root
  become_method: sudo

