---

- name: Install Xorg & DEs
  apt: pkg={{ item }} state=latest
  with_items:
      - xorg
      - xinit
      - i3
      - slim
  notify: enable slim
  become: yes
  become_user: root
  become_method: sudo

- name: Install X-Related Utilities
  apt: pkg={{ item }} state=latest
  with_items:
      - pcmanfm
      - atril
      - rofi
      - pavucontrol
      - pasystray
      - redshift-gtk
      - synapse
      - feh
      - compton
      - pulseaudio
      - compton
      - mpv
      - xautolock
      - scrot
      - blueman
      - pulseaudio-module-bluetooth
      - geeqie
      - vim-gtk3
      - thunderbird
      - dbus
      - mate-calc
      - network-manager
      - network-manager-gnome
      - arandr
      - firefox-esr
      - rxvt-unicode-256color
      - pinta

  become: yes
  become_user: root
  become_method: sudo

- name: Enable dbus
  service: name=dbus state=started enabled=yes
  become: yes
  become_user: root
  become_method: sudo

- name: Enable network-manager
  service: name=network-manager state=started enabled=yes
  become: yes
  become_user: root
  become_method: sudo

- name: Install MPD
  notify: enable mpd
  become: yes
  become_user: root
  become_method: sudo
  apt: pkg={{ item }} state=latest
  with_items:
      - mpd
      - mpc
      - cantata

- name: Setup MPD Service
  shell: "systemctl enable --user mpd.service && systemctl start --user mpd.service"

- name: Ensure home bin Exists
  file: path={{ ansible_env.HOME }}/bin state=directory

- name: Install System Scripts
  copy: src={{ role_path }}/templates/scripts/{{ item }} dest={{ ansible_env.HOME}}/bin/{{ item }} mode=a+x
  with_items:
    - system-configure-iptables
    - system-launch-compositor
    - system-lock
    - system-reset-xhci
    - system-screenshot
    - system-statusline

- name: Ensure opt bin directory exists
  file: path=/opt/net.cdaniels/bin state=directory
  become: yes
  become_user: root
  become_method: sudo

- name: Install System Scripts to opt
  copy: src={{ role_path }}/templates/scripts/{{ item }} dest=/opt/net.cdaniels/bin/{{ item }} mode=a+x
  with_items:
      - system-reset-xhci
      - system-lock
      - system-configure-iptables
  become: yes
  become_user: root
  become_method: sudo

- name: Enable Services
  service: name={{ item }}.service enabled=yes
  become: yes
  become_user: root
  become_method: sudo
  with_items:
      - bluetooth

- name: Download CybeChef
  get_url:
      url: https://gchq.github.io/CyberChef/cyberchef.htm
      dest: "{{ ansible_env.HOME}}/.local/share/setupsoftware/cyberchef.htm"
      mode: 0644

- name: Install Snaps
  command: snap install {{ item }}
  with_items:
      - chromium
  become: yes
  become_user: root
  become_method: sudo

- name: Delete 70-no-bitmaps
  file:
      path: /etc/fonts/conf.d/70-yes-bitmaps.conf
      state: absent
  become: yes
  become_user: root
  become_method: sudo

- name: Enable bitmaps
  file:
      src: /usr/share/fontconfig/conf.avail/70-yes-bitmaps.conf
      dest: /etc/fonts/conf.d/70-yes-bitmaps.conf
      state: link
  become: yes
  become_user: root
  become_method: sudo

- name: Download GohuFont
  get_url:
      url: "http://font.gohu.org/gohufont-2.1.tar.gz"
      dest: "{{setupsoftware_dir}}/gohufont.tar.gz"

- name: Install GohuFont
  unarchive:
      src: "{{setupsoftware_dir}}/gohufont.tar.gz"
      dest: /usr/share/fonts/
  become: yes
  become_user: root
  become_method: sudo

- name: Refresh Font Cache
  shell: "fc-cache -f -v"
  become: yes
  become_user: root
  become_method: sudo
