---

- name: Install Xorg & DEs
  apt: pkg={{ item }} state=latest
  with_items:
      - xorg
      - xinit
      - xdm
  notify: enable xdm
  become: yes
  become_user: root
  become_method: sudo

- name: Install X-Related Utilities
  apt: pkg={{ item }} state=latest
  with_items:
      - adwaita-icon-theme-full
      - adwaita-qt
      - arandr
      - atril
      - caja
      - calibre
      - compton
      - dbus
      - dconf-editor
      - dconf-cli
      - engrampa
      - evolution
      - feh
      - firefox
      - geeqie
      - gnome-themes-extra
      - goldendict
      - goldendict-wordnet
      - keepassxc
      - libreoffice
      - mate-control-center
      - mate-settings-daemon
      - mpv
      - musique
      - network-manager
      - network-manager-gnome
      - numlockx
      - pavucontrol
      - pinta
      - pulseaudio
      - redshift
      - remmina
      - remmina-plugin-rdp
      - remmina-plugin-vnc
      - scrot
      - stalonetray
      - steam
      - system-config-printer
      - vim-gtk3
      - winetricks
      - xautolock
      - xtrlock
      - xbacklight
      - xclip
      - xfburn
      - xdotool
      - xkbset

  become: yes
  become_user: root
  become_method: sudo

- name: Install WINE
  apt: pkg={{ item }} state=latest install_recommends=true
  with_items:
      - winehq-stable
  become: yes
  become_user: root
  become_method: sudo

- name: Enable dbus
  service: name=dbus state=started enabled=yes
  become: yes
  become_user: root
  become_method: sudo

- name: Enable network-manager
  service: name=network-manager state=started enabled=yes
  become: yes
  become_user: root
  become_method: sudo

- name: Ensure home bin Exists
  file: path={{ ansible_env.HOME }}/bin state=directory

- name: Ensure opt bin directory exists
  file: path=/opt/net.cdaniels/bin state=directory
  become: yes
  become_user: root
  become_method: sudo

- name: Install System Scripts to opt
  copy: src={{ role_path }}/templates/scripts/{{ item }} dest=/opt/net.cdaniels/bin/{{ item }} mode=a+x
  with_items:
      - system-reset-xhci
  become: yes
  become_user: root
  become_method: sudo

- name: Download CybeChef
  get_url:
      url: https://gchq.github.io/CyberChef/cyberchef.htm
      dest: "{{ ansible_env.HOME}}/.local/share/setupsoftware/cyberchef.htm"
      mode: 0644

- name: Delete 70-no-bitmaps
  file:
      path: /etc/fonts/conf.d/70-no-bitmaps.conf
      state: absent
  become: yes
  become_user: root
  become_method: sudo

- name: Install GohuFont
  unarchive:
      src: "http://font.gohu.org/gohufont-2.1.tar.gz"
      dest: /usr/share/fonts/
      remote_src: true
      creates: "/usr/share/fonts/gohufont-2.1"
  become: yes
  become_user: root
  become_method: sudo

- name: Refresh Font Cache
  shell: "fc-cache -f -v"
  become: yes
  become_user: root
  become_method: sudo

- name: Create Arduino IDE Install Directory
  file:
    path: "/opt/arduino"
    state: directory
  become: yes
  become_user: root
  become_method: sudo

- name: Install Arduino IDE
  unarchive:
      src: "https://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz"
      dest: "/opt/arduino/"
      remote_src: true
      creates: "/opt/arduino/arduino-1.8.5"
  become: yes
  become_user: root
  become_method: sudo

- name: Link Arduino IDE Binaries
  file:
      src: "/opt/arduino/arduino-1.8.5/{{ item }}"
      dest: "/usr/local/bin/{{ item }}"
      state: link
  with_items:
      - arduino
      - arduino-builder
  become: yes
  become_user: root
  become_method: sudo

- name: Disable systemd-networkd-wait-online.service
  command: systemctl disable systemd-networkd-wait-online.service
  become: yes
  become_user: root
  become_method: sudo

- name: Mask systemd-networkd-wait-online.service
  command: systemctl mask systemd-networkd-wait-online.service
  become: yes
  become_user: root
  become_method: sudo

- name: install lock script
  template:
    src: lock.j2
    dest: /lib/systemd/system-sleep/lock
    owner: root
    mode: 0755
    group: root
  become: yes
  become_user: root
  become_method: sudo
