---
- name: Install Services
  template: src={{ item }}.service.j2 dest=/etc/systemd/system/{{ item }}.service
  become: yes
  become_user: root
  become_method: sudo
  with_items:
      - lockscreen
      - iptables_config

- name: Enable Services
  service: name={{ item }}.service enabled=yes
  become: yes
  become_user: root
  become_method: sudo
  with_items:
      - lockscreen
      - iptables_config

