---
- name: Ensure Repos Directory Exists
  file: path={{setupsoftware_dir}} state=directory

- name: Extract exa
  unarchive:
      src: "https://github.com/ogham/exa/releases/download/v0.8.0/exa-linux-x86_64-0.8.0.zip"
      dest: "{{setupsoftware_dir}}/"
      remote_src: true
      creates: "{{setupsoftware_dir}}/exa-linux-x86_64"

- name: Install exa
  copy:
      src: "{{setupsoftware_dir}}/exa-linux-x86_64"
      dest: "/usr/local/bin/exa"
      mode: 751
  become: yes
  become_user: root
  become_method: sudo

- name: Install ripgrep
  apt:
      deb: "https://github.com/BurntSushi/ripgrep/releases/download/0.9.0/ripgrep_0.9.0_amd64.deb"
  become: yes
  become_user: root
  become_method: sudo

- name: Install fd-find
  apt:
      deb: "https://github.com/sharkdp/fd/releases/download/v7.0.0/fd_7.0.0_amd64.deb"
  become: yes
  become_user: root
  become_method: sudo

- name: Extract tin-summer
  unarchive:
      src: "https://github.com/vmchale/tin-summer/releases/download/1.21.5/tin-summer-1.21.5-x86_64-unknown-linux-gnu.tar.gz"
      dest: "{{setupsoftware_dir}}/"
      creates: "{{setupsoftware_dir}}/sn"
      remote_src: true

- name: Install tin-summer
  copy:
      src: "{{setupsoftware_dir}}/sn"
      dest: "/usr/local/bin/sn"
      mode: 751
  become: yes
  become_user: root
  become_method: sudo

- name: Install tokei
  apt:
      deb: "https://github.com/Aaronepower/tokei/releases/download/v6.0.0/tokei-v6.0.0-x86_64-unknown-linux-gnu.deb"
  become: yes
  become_user: root
  become_method: sudo

- name: Install Rust
  shell: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
  args:
    warn: false
  changed_when: false
