---
- name: Install sources.list
  template:
      src: sources.list
      dest: /etc/apt/sources.list
      mode: 0644
  become_user: root
  become_method: sudo
  become: yes

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
  become_user: root
  become_method: sudo
  become: yes

- name: Early Dependencies
  apt: pkg={{ item }} state=latest
  with_items:
      - apt-transport-https
  become_user: root
  become_method: sudo
  become: yes

- name: add PowerShell Repository
  apt: "deb=https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb"
  become_user: root
  become_method: sudo
  become: yes

- name: Add i386 Architecture
  command: "dpkg --add-architecture i386"
  become: yes
  become_user: root
  become_method: sudo

- name: Add WINE Apt Key
  apt_key:
      url: "https://dl.winehq.org/wine-builds/winehq.key"
      state: present
  become: yes
  become_user: root
  become_method: sudo

- name: Add WINE repository
  apt_repository:
      repo: "deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main"
      state: present
      update_cache: true
  become: yes
  become_user: root
  become_method: sudo

- name: update apt cache
  apt:
    update_cache: yes
  become_user: root
  become_method: sudo
  become: yes

- name: CLI tools
  apt: pkg={{ item }} state=latest
  with_items:
      - acpi
      - aptitude
      - bash
      - bison
      - build-essential
      - cmake
      - ctags
      - curl
      - dnsutils
      - finger
      - flex
      - git
      - gnuplot
      - groff
      - htop
      - imagemagick
      - iotop
      - libconfig-tiny-perl
      - libfile-path-expand-perl
      - libfilesys-df-perl
      - libnet-address-ip-local-perl
      - libnumber-bytes-human-perl
      - libpar-packer-perl
      - libsys-meminfo-perl
      - libtimedate-perl
      - links2
      - lm-sensors
      - man-db
      - mksh
      - nasm
      - net-tools
      - netcat
      - neovim
      - nload
      - nmap
      - openjdk-8-jdk
      - openjdk-8-jre
      - p7zip
      - pandoc
      - pkg-config
      - powershell
      - powertop
      - python
      - python-pip
      - python3
      - python3-pip
      - python3-sphinx
      - python3-virtualenv
      - ragel
      - ranger
      - rfkill
      - ripgrep
      - slurm
      - sshfs
      - surfraw
      - tmux
      - tokei
      - tree
      - txt2man
      - units
      - unzip
      - upower
      - upx-ucl
      - youtube-dl
      - zsh
  become: yes
  become_user: root
  become_method: sudo

- name: System Services and Drivers
  apt: pkg={{ item }} state=latest
  with_items:
      - snapd
      - bluez
  become: yes
  become_user: root
  become_method: sudo

- name: Enable snapd
  service: name=snapd state=started enabled=yes
  become: yes
  become_user: root
  become_method: sudo

- name: Libraries
  apt: pkg={{ item }} state=latest
  with_items:
      - libboost1.62-dev
      - libbsd-dev
      - libfltk1.3
      - libfltk1.3-dev
      - libfontconfig1
      - libfontconfig1-dev
      - libfreetype6
      - libfreetype6-dev
      - libgit2-dev
      - libsqlite3-dev
      - libssh2-1-dev
      - libssl-dev
      - libx11-6
      - libx11-dev
      - libxext-dev
      - libxext6
      - libxft-dev
      - libxft2
      - openssl
      - python-psutil
      - python3-humanize
      - python3-lxml
      - python3-matplotlib
      - python3-numpy
      - python3-psutil
      - python3-recommonmark
      - python3-scipy
      - python3-tabulate
      - python3-taglib
      - python3-yaml
      - sqlite3

  become: yes
  become_user: root
  become_method: sudo

- name: Install TI udev rules
  get_url:
      dest: /etc/udev/rules.d/71-ti-permissions.rules
      url: 'https://s3.amazonaws.com/energiaUS/files/71-ti-permissions.rules'
      mode: 0644
  become: yes
  become_user: root
  become_method: sudo

- name: Install modules from pip
  # TODO: it would be preferable to not do a global pip install
  shell: pip3 install {{ item}}
  with_items:
      - pyinstaller
  become: yes
  become_user: root
  become_method: sudo
