---
- name: Install sources.list
  template:
      src: sources.list
      dest: /etc/apt/sources.list
      mode: 0644
  become_user: root
  become_method: sudo
  become: yes

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
  become_user: root
  become_method: sudo
  become: yes

- name: Early Dependencies
  apt: pkg={{ item }} state=latest
  with_items:
      - apt-transport-https

- name: Add PowerShell Apt Key
  apt_key:
      url: "https://packages.microsoft.com/keys/microsoft.asc"
      state: "present"
  become: yes
  become_user: root
  become_method: sudo

- name: Add PowerShell Repository
  apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main"
      state: present
      update_cache: true
  become: yes
  become_user: root
  become_method: sudo

- name: Add i386 Architecture
  command: "dpkg --add-architecture i386"
  become: yes
  become_user: root
  become_method: sudo

- name: Add WINE Apt Key
  apt_key:
      url: "https://dl.winehq.org/wine-builds/Release.key"
      state: present
  become: yes
  become_user: root
  become_method: sudo

- name: Add WINE repository
  apt_repository:
      repo: "deb https://dl.winehq.org/wine-builds/debian/ stretch main"
      state: present
      update_cache: true
  become: yes
  become_user: root
  become_method: sudo

- name: CLI tools
  apt: pkg={{ item }} state=latest
  with_items:
      - vim
      - zsh
      - python
      - python-pip
      - python3
      - python3-pip
      - htop
      - tmux
      - slurm
      - nload
      - nmap
      - netcat
      - iotop
      - bash
      - build-essential
      - git
      - tree
      - imagemagick
      - youtube-dl
      - lm-sensors
      - texlive
      - python3-sphinx
      - curl
      - pkg-config
      - cmake
      - surfraw
      - links2
      - bison
      - flex
      - sshfs
      - powershell
      - aptitude
      - glances
      - dnsutils
      - finger
      - net-tools
      - gnuplot
      - upower
      - powertop
      - acpi
      - nasm
      - ragel
      - rfkill
      - units
      - ctags

  become: yes
  become_user: root
  become_method: sudo

- name: System Services and Drivers
  apt: pkg={{ item }} state=latest
  with_items:
      - snapd
      - bluez
  become: yes
  become_user: root
  become_method: sudo

- name: Enable snapd
  service: name=snapd state=started enabled=yes
  become: yes
  become_user: root
  become_method: sudo

- name: Libraries
  apt: pkg={{ item }} state=latest
  with_items:
      - python3-yaml
      - python-psutil
      - python3-psutil
      - python3-numpy
      - python3-scipy
      - python3-matplotlib
      - python3-recommonmark
      - python3-tabulate
      - python3-humanize
      - python3-taglib
      - libgit2-dev
      - libssh2-1-dev
      - libssl-dev
      - openssl
      - libboost1.62-dev
      - sqlite3
      - libsqlite3-dev
      - python3-lxml

  become: yes
  become_user: root
  become_method: sudo

- name: Install TI udev rules
  get_url:
      dest: /etc/udev/rules.d/71-ti-permissions.rules
      url: 'https://s3.amazonaws.com/energiaUS/files/71-ti-permissions.rules'
      mode: 0644
  become: yes
  become_user: root
  become_method: sudo
