---
- name: CLI tools
  apt: pkg={{ item }} state=latest
  with_items:
      - texlive
      - latexmk
      - texlive-latex-extra
      - texlive-science
      - texlive-fonts-extra

  become: yes
  become_user: root
  become_method: sudo
